// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbU_EySyYwV9Na8eZLjiCSzwjmbipH4cM',
    appId: '1:1082391834530:web:e16df89c40ec38229c8cfb',
    messagingSenderId: '1082391834530',
    projectId: 'post-app-2b9c3',
    authDomain: 'post-app-2b9c3.firebaseapp.com',
    storageBucket: 'post-app-2b9c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2w673uflheDVXRkUYbnV-iM0elI6Mtc4',
    appId: '1:1082391834530:android:94bb6475cde264879c8cfb',
    messagingSenderId: '1082391834530',
    projectId: 'post-app-2b9c3',
    storageBucket: 'post-app-2b9c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCc8jiyYYEo0LmVqgXmMAg1dwR2LYzWrw',
    appId: '1:1082391834530:ios:c0762e076ba7af399c8cfb',
    messagingSenderId: '1082391834530',
    projectId: 'post-app-2b9c3',
    storageBucket: 'post-app-2b9c3.appspot.com',
    iosBundleId: 'com.example.postApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCc8jiyYYEo0LmVqgXmMAg1dwR2LYzWrw',
    appId: '1:1082391834530:ios:4bcd6c9e2136fd5f9c8cfb',
    messagingSenderId: '1082391834530',
    projectId: 'post-app-2b9c3',
    storageBucket: 'post-app-2b9c3.appspot.com',
    iosBundleId: 'com.example.postApp.RunnerTests',
  );
}
